<a href="https://colab.research.google.com/github/Hyeseong0317/Pytorch_Capstone_Design/blob/main/pytorch_backward_comprehension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

변수선언(+데이터 입력) -> 모델 내 연산 예측값 산출 -> 손실함수 계산 -> 손실 산출

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [4]:
z = 2*y**2
res = z.mean()

In [5]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [6]:
# d(res)/dx_i = x_i +1

# res = (z_1 + .. + z_4) / 4
# z_i = 2 y_i **2
# z_i = 2(x_i+1)**2

res.backward()

In [7]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [8]:
import torch.nn as nn
import torch.nn.functional as F